package com.siu.android.demos.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.IdentityScopeType;

import com.siu.android.demos.model.DemoModel;

import com.siu.android.demos.model.DemoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig demoModelDaoConfig;

    private final DemoModelDao demoModelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        demoModelDaoConfig = daoConfigMap.get(DemoModelDao.class).clone();
        demoModelDaoConfig.initIdentityScope(type);

        demoModelDao = new DemoModelDao(demoModelDaoConfig, this);

        registerDao(DemoModel.class, demoModelDao);
    }
    
    public void clear() {
        demoModelDaoConfig.getIdentityScope().clear();
    }

    public DemoModelDao getDemoModelDao() {
        return demoModelDao;
    }

}
