package com.siu.android.demos.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table DEMO_MODEL.
 */
public class DemoModel implements java.io.Serializable {

    private Long id;
    private String webserviceId;
    private String name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public DemoModel() {
    }

    public DemoModel(Long id) {
        this.id = id;
    }

    public DemoModel(Long id, String webserviceId, String name) {
        this.id = id;
        this.webserviceId = webserviceId;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getWebserviceId() {
        return webserviceId;
    }

    public void setWebserviceId(String webserviceId) {
        this.webserviceId = webserviceId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
